version: '3'

services:

  php:
    build:
      context: './php/'
    volumes: 
      - ./app/:/var/www/
    networks: 
      - backend
    ports: 
      - '9000:9000'
    container_name: phpfpm

  mariadb:
    build: 
      context: './db/'
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=teste
      - MYSQL_USER=sergio
      - MYSQL_PASSWORD=123456
    volumes:
      - ./db/data/:/var/lib/mysql/
      - ./db/sql/:/docker-entrypoint-initdb.d
    networks: 
      - backend
    ports: 
      - '3306:3306'
    container_name: database

  nginx:
    build: 
      context: './webserver/'
    depends_on: 
      - php
      - mariadb
    volumes: 
      - ./app/:/var/www/
    networks: 
      - backend
      - frontend
    ports: 
      - '80:80'
      - '443:443'
    container_name: webserver

networks:
  backend:
    driver: 'bridge'
  frontend:
    driver: 'bridge'